### ISSUE TITLE
bug with installation

### ISSUE THREAD

**Issue by ScarlettQGG** [grosenberger/secat#8]
Getting error when installing the package:

× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

Can you see if there is something you can help? 
Thank you.

**Comment by dgorhe** [comment]
Hey there!

Sorry for the late reply to this issue. I was able to reproduce the issue using the conda instructions. Which installation method did you use? Are you setting up the secat conda environment first or installing without conda? Also, are you installing from the master branch or from PyPI (i.e. `pip install git+https://github.com/grosenberger/secat.git@master` or `pip install secat`)?

I was able to fix the immediate issue in my fork, but I'm running into issues with `minepy` when I try to run SECAT. To solve the immediate issue, you can follow the conda instructions in the README to set up the `secat` environment. Then run:

```bash
pip install git+https://github.com/dgorhe/secat.git@master
```

Note that this is from my fork (dgorhe) instead of the main repo (grosenberger). The installation will complete but if you run:

```bash
secat --help
```

You might see something like this:

```
Traceback (most recent call last):
  File "/Users/darveshgorhe/miniforge3/envs/secat/bin/secat", line 5, in <module>
    from secat.main import cli
  File "/Users/darveshgorhe/miniforge3/envs/secat/lib/python3.10/site-packages/secat/main.py", line 12, in <module>
    from .score import monomer, scoring
  File "/Users/darveshgorhe/miniforge3/envs/secat/lib/python3.10/site-packages/secat/score.py", line 14, in <module>
    from minepy import cstats
  File "/Users/darveshgorhe/miniforge3/envs/secat/lib/python3.10/site-packages/minepy/__init__.py", line 1, in <module>
    from .mine import MINE, pstats, cstats
  File "minepy/mine.pyx", line 1, in init minepy.mine
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

I don't have time in the next couple of days to fix this, but I will update this thread as soon as I make progress. Feel free to keep up with the updates here: https://github.com/dgorhe/secat
